package com.yanhuo.sign.dal.DTO;

import lombok.Data;
import org.hibernate.validator.constraints.NotEmpty;

import javax.validation.constraints.Size;
import java.io.Serializable;

/**
 * @author 烟火（yanhuo@maihaoche.com）
 * @version V1.0
 * @Description: TODO
 * @date 2018/5/5 上午10:06
 */
@Data
public class TeacherDTO implements Serializable {

    /**
     * 教师Id
     */
    private Long uId;

    /**
     * 教师用户名
     */
    @NotEmpty(message = "姓名不能为空")
    @Size(min = 2,max = 8,message = "姓名长度必须介于2到20字之间")
    private String uName;

    /**
     * 性别
     */
    private Boolean uSex;

    /**
     * 学院
     */
    private String uInstitute;

    /**
     * 权限
     */
    private Integer uPower;

    /**
     * 邮箱
     */
    private String uEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;
}
