server:
  port: 8080

spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/sign?useUnicode=true&characterEncoding=UTF-8
        username: root
        password: xihanzhiwen
        #配置监控统计拦截的filters，去掉监控界面sql将无法统计，'wall'用于防火墙
        filters: stat,wall,log4j
        #最大活跃数
        maxActive: 20
        #初始化数量
        initialSize: 1
        #最大连接等待时间
        maxWait: 60000
        #打开PSCache，并且指定每个连接PSCache的大小
        pool-prepared-statements: true
        maxPoolPreparesStatementPerConnectionSize: 20
        #通过coonectionProperties属性来打开mergeSql功能，慢SQL记录
        connectiobProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        minldle: 1
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        validation-query: select 1 from dual
        test-while-idle: true
        testOnBorrow: false
        testOnReturn: false
    #thymeleaf配置
    thymealeaf:
         enabled: true
         prefix: classpath:/templstes/
         sufffix: .html
         content-type: text/html
         encoding: UTF-8
         check-template-location: false
         #mode: HTML5
         mode: LEGACYHTML5
         cache: false
    mail:
      host: smtp.qq.com
      username: 1634447610@qq.com
      password: wdaroevmsgpzghjf
      properties:
         mail:
           smtp:
             auth: true
             starttls: true
mybatis:
  config-location: classpath:mybatis-config.xml