package com.yanhuo.sign.dal.mapper;

import com.yanhuo.sign.dal.model.TeacherSignRecord;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface TeacherSignRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_sign_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer recordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_sign_record
     *
     * @mbggenerated
     */
    int insert(TeacherSignRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_sign_record
     *
     * @mbggenerated
     */
    TeacherSignRecord selectByPrimaryKey(Integer recordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_sign_record
     *
     * @mbggenerated
     */
    List<TeacherSignRecord> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_sign_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TeacherSignRecord record);
}