package com.yanhuo.sign.dal.model;

import java.io.Serializable;

public class StudentInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.s_id
     *
     * @mbggenerated
     */
    private Integer sId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.s_no
     *
     * @mbggenerated
     */
    private String sNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.s_name
     *
     * @mbggenerated
     */
    private String sName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.s_class
     *
     * @mbggenerated
     */
    private Long sClass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.s_sex
     *
     * @mbggenerated
     */
    private Boolean sSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table student_info
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.s_id
     *
     * @return the value of student_info.s_id
     *
     * @mbggenerated
     */
    public Integer getsId() {
        return sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.s_id
     *
     * @param sId the value for student_info.s_id
     *
     * @mbggenerated
     */
    public void setsId(Integer sId) {
        this.sId = sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.s_no
     *
     * @return the value of student_info.s_no
     *
     * @mbggenerated
     */
    public String getsNo() {
        return sNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.s_no
     *
     * @param sNo the value for student_info.s_no
     *
     * @mbggenerated
     */
    public void setsNo(String sNo) {
        this.sNo = sNo == null ? null : sNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.s_name
     *
     * @return the value of student_info.s_name
     *
     * @mbggenerated
     */
    public String getsName() {
        return sName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.s_name
     *
     * @param sName the value for student_info.s_name
     *
     * @mbggenerated
     */
    public void setsName(String sName) {
        this.sName = sName == null ? null : sName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.s_class
     *
     * @return the value of student_info.s_class
     *
     * @mbggenerated
     */
    public Long getsClass() {
        return sClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.s_class
     *
     * @param sClass the value for student_info.s_class
     *
     * @mbggenerated
     */
    public void setsClass(Long sClass) {
        this.sClass = sClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.s_sex
     *
     * @return the value of student_info.s_sex
     *
     * @mbggenerated
     */
    public Boolean getsSex() {
        return sSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.s_sex
     *
     * @param sSex the value for student_info.s_sex
     *
     * @mbggenerated
     */
    public void setsSex(Boolean sSex) {
        this.sSex = sSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_info
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", sId=").append(sId);
        sb.append(", sNo=").append(sNo);
        sb.append(", sName=").append(sName);
        sb.append(", sClass=").append(sClass);
        sb.append(", sSex=").append(sSex);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}