package com.yanhuo.sign.dal.model;

import java.io.Serializable;

public class TeacherSignRecord implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_sign_record.record_id
     *
     * @mbggenerated
     */
    private Integer recordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_sign_record.t_id
     *
     * @mbggenerated
     */
    private Integer tId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_sign_record.sign_record_no
     *
     * @mbggenerated
     */
    private Integer signRecordNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table teacher_sign_record
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_sign_record.record_id
     *
     * @return the value of teacher_sign_record.record_id
     *
     * @mbggenerated
     */
    public Integer getRecordId() {
        return recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_sign_record.record_id
     *
     * @param recordId the value for teacher_sign_record.record_id
     *
     * @mbggenerated
     */
    public void setRecordId(Integer recordId) {
        this.recordId = recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_sign_record.t_id
     *
     * @return the value of teacher_sign_record.t_id
     *
     * @mbggenerated
     */
    public Integer gettId() {
        return tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_sign_record.t_id
     *
     * @param tId the value for teacher_sign_record.t_id
     *
     * @mbggenerated
     */
    public void settId(Integer tId) {
        this.tId = tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_sign_record.sign_record_no
     *
     * @return the value of teacher_sign_record.sign_record_no
     *
     * @mbggenerated
     */
    public Integer getSignRecordNo() {
        return signRecordNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_sign_record.sign_record_no
     *
     * @param signRecordNo the value for teacher_sign_record.sign_record_no
     *
     * @mbggenerated
     */
    public void setSignRecordNo(Integer signRecordNo) {
        this.signRecordNo = signRecordNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_sign_record
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", recordId=").append(recordId);
        sb.append(", tId=").append(tId);
        sb.append(", signRecordNo=").append(signRecordNo);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}