package com.yanhuo.sign.dal.model;

import java.io.Serializable;

public class User implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_id
     *
     * @mbggenerated
     */
    private Long uId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_name
     *
     * @mbggenerated
     */
    private String uName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_pwd
     *
     * @mbggenerated
     */
    private String uPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_sex
     *
     * @mbggenerated
     */
    private Boolean uSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.open_id
     *
     * @mbggenerated
     */
    private String openId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_institute
     *
     * @mbggenerated
     */
    private String uInstitute;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_power
     *
     * @mbggenerated
     */
    private Integer uPower;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_email
     *
     * @mbggenerated
     */
    private String uEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.s_no
     *
     * @mbggenerated
     */
    private String sNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_id
     *
     * @return the value of user.u_id
     *
     * @mbggenerated
     */
    public Long getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_id
     *
     * @param uId the value for user.u_id
     *
     * @mbggenerated
     */
    public void setuId(Long uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_name
     *
     * @return the value of user.u_name
     *
     * @mbggenerated
     */
    public String getuName() {
        return uName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_name
     *
     * @param uName the value for user.u_name
     *
     * @mbggenerated
     */
    public void setuName(String uName) {
        this.uName = uName == null ? null : uName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_pwd
     *
     * @return the value of user.u_pwd
     *
     * @mbggenerated
     */
    public String getuPwd() {
        return uPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_pwd
     *
     * @param uPwd the value for user.u_pwd
     *
     * @mbggenerated
     */
    public void setuPwd(String uPwd) {
        this.uPwd = uPwd == null ? null : uPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_sex
     *
     * @return the value of user.u_sex
     *
     * @mbggenerated
     */
    public Boolean getuSex() {
        return uSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_sex
     *
     * @param uSex the value for user.u_sex
     *
     * @mbggenerated
     */
    public void setuSex(Boolean uSex) {
        this.uSex = uSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.open_id
     *
     * @return the value of user.open_id
     *
     * @mbggenerated
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.open_id
     *
     * @param openId the value for user.open_id
     *
     * @mbggenerated
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_institute
     *
     * @return the value of user.u_institute
     *
     * @mbggenerated
     */
    public String getuInstitute() {
        return uInstitute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_institute
     *
     * @param uInstitute the value for user.u_institute
     *
     * @mbggenerated
     */
    public void setuInstitute(String uInstitute) {
        this.uInstitute = uInstitute == null ? null : uInstitute.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_power
     *
     * @return the value of user.u_power
     *
     * @mbggenerated
     */
    public Integer getuPower() {
        return uPower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_power
     *
     * @param uPower the value for user.u_power
     *
     * @mbggenerated
     */
    public void setuPower(Integer uPower) {
        this.uPower = uPower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_email
     *
     * @return the value of user.u_email
     *
     * @mbggenerated
     */
    public String getuEmail() {
        return uEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_email
     *
     * @param uEmail the value for user.u_email
     *
     * @mbggenerated
     */
    public void setuEmail(String uEmail) {
        this.uEmail = uEmail == null ? null : uEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.s_no
     *
     * @return the value of user.s_no
     *
     * @mbggenerated
     */
    public String getsNo() {
        return sNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.s_no
     *
     * @param sNo the value for user.s_no
     *
     * @mbggenerated
     */
    public void setsNo(String sNo) {
        this.sNo = sNo == null ? null : sNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", uId=").append(uId);
        sb.append(", uName=").append(uName);
        sb.append(", uPwd=").append(uPwd);
        sb.append(", uSex=").append(uSex);
        sb.append(", openId=").append(openId);
        sb.append(", uInstitute=").append(uInstitute);
        sb.append(", uPower=").append(uPower);
        sb.append(", uEmail=").append(uEmail);
        sb.append(", sNo=").append(sNo);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}