package com.yanhuo.sign.dal.VO;

import java.io.Serializable;

public class SignVO  implements Serializable {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column sign.sign_id
         *
         * @mbggenerated
         */
        private Long signId;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column sign.begin_sign_time
         *
         * @mbggenerated
         */
        private String beginSignTime;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column sign.s_id
         *
         * @mbggenerated
         */
        private String  sName;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column sign.c_name
         *
         * @mbggenerated
         */
        private String cName;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column sign.c_location
         *
         * @mbggenerated
         */
        private String cLocation;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column sign.is_sign
         *
         * @mbggenerated
         */
        private String isSign;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column sign.sign_time
         *
         * @mbggenerated
         */
        private String signTime;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column sign.t_name
         *
         * @mbggenerated
         */
        private String tName;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column sign.t_id
         *
         * @mbggenerated
         */
        private Integer tId;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column sign.sign_num
         *
         * @mbggenerated
         */
        private Integer signNum;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column sign.s_class
         *
         * @mbggenerated
         */
        private Long sClass;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column sign.open_id
         *
         * @mbggenerated
         */
        private String openId;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table sign
         *
         * @mbggenerated
         */
        private static final long serialVersionUID = 1L;

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column sign.sign_id
         *
         * @return the value of sign.sign_id
         *
         * @mbggenerated
         */
        public Long getSignId() {
            return signId;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column sign.sign_id
         *
         * @param signId the value for sign.sign_id
         *
         * @mbggenerated
         */
        public void setSignId(Long signId) {
            this.signId = signId;
        }

    @Override
    public String toString() {
        return "SignVO{" +
                "signId=" + signId +
                ", beginSignTime='" + beginSignTime + '\'' +
                ", sName='" + sName + '\'' +
                ", cName='" + cName + '\'' +
                ", cLocation='" + cLocation + '\'' +
                ", isSign='" + isSign + '\'' +
                ", signTime='" + signTime + '\'' +
                ", tName='" + tName + '\'' +
                ", tId=" + tId +
                ", signNum=" + signNum +
                ", sClass=" + sClass +
                ", openId='" + openId + '\'' +
                '}';
    }

    public String getBeginSignTime() {
        return beginSignTime;
    }

    public void setBeginSignTime(String beginSignTime) {
        this.beginSignTime = beginSignTime;
    }

    public String getsName() {
        return sName;
    }

    public void setsName(String sName) {
        this.sName = sName;
    }

    public String getIsSign() {
        return isSign;
    }

    public void setIsSign(String isSign) {
        this.isSign = isSign;
    }

    public String getSignTime() {
        return signTime;
    }

    public void setSignTime(String signTime) {
        this.signTime = signTime;
    }

    public static long getSerialVersionUID() {
        return serialVersionUID;
    }

    /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column sign.begin_sign_time
         *
         * @return the value of sign.begin_sign_time
         *
         * @mbggenerated




        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column sign.c_name
         *
         * @return the value of sign.c_name
         *
         * @mbggenerated
         */
        public String getcName() {
            return cName;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column sign.c_name
         *
         * @param cName the value for sign.c_name
         *
         * @mbggenerated
         */
        public void setcName(String cName) {
            this.cName = cName == null ? null : cName.trim();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column sign.c_location
         *
         * @return the value of sign.c_location
         *
         * @mbggenerated
         */
        public String getcLocation() {
            return cLocation;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column sign.c_location
         *
         * @param cLocation the value for sign.c_location
         *
         * @mbggenerated
         */
        public void setcLocation(String cLocation) {
            this.cLocation = cLocation == null ? null : cLocation.trim();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column sign.is_sign
         *
         * @return the value of sign.is_sign
         *
         * @mbggenerated
         */



        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column sign.t_name
         *
         * @return the value of sign.t_name
         *
         * @mbggenerated
         */
        public String gettName() {
            return tName;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column sign.t_name
         *
         * @param tName the value for sign.t_name
         *
         * @mbggenerated
         */
        public void settName(String tName) {
            this.tName = tName == null ? null : tName.trim();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column sign.t_id
         *
         * @return the value of sign.t_id
         *
         * @mbggenerated
         */
        public Integer gettId() {
            return tId;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column sign.t_id
         *
         * @param tId the value for sign.t_id
         *
         * @mbggenerated
         */
        public void settId(Integer tId) {
            this.tId = tId;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column sign.sign_num
         *
         * @return the value of sign.sign_num
         *
         * @mbggenerated
         */
        public Integer getSignNum() {
            return signNum;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column sign.sign_num
         *
         * @param signNum the value for sign.sign_num
         *
         * @mbggenerated
         */
        public void setSignNum(Integer signNum) {
            this.signNum = signNum;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column sign.s_class
         *
         * @return the value of sign.s_class
         *
         * @mbggenerated
         */
        public Long getsClass() {
            return sClass;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column sign.s_class
         *
         * @param sClass the value for sign.s_class
         *
         * @mbggenerated
         */
        public void setsClass(Long sClass) {
            this.sClass = sClass;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column sign.open_id
         *
         * @return the value of sign.open_id
         *
         * @mbggenerated
         */
        public String getOpenId() {
            return openId;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column sign.open_id
         *
         * @param openId the value for sign.open_id
         *
         * @mbggenerated
         */
        public void setOpenId(String openId) {
            this.openId = openId == null ? null : openId.trim();
        }



}
